### PR TITLE
Color scheme2

### LINKED ISSUE #18: Pick fonts
This isn't necessarily a quick and easy task. Do some research and learn about some methods of picking.
https://www.youtube.com/watch?v=Xwahw7mdeXQ

I'm hoping for 2 fonts, one for titles and the other for the body.

I usually source my fonts from Google Fonts

### LINKED ISSUE #19: Define colors
We need a colour palette, something similar to the current yegrb.com.

Bootstrap has a default colour scheme. Never use the default :) (Or else you will look like every other website). We need 2 or 3 nice shades of colour that go well together and a bunch of shades of grey that go from almost white to almost black. Please make your colours HSLA, VS Code can convert the colours for you.

Use this to define colors: https://coolors.co/
Define the colors in Bootstrap: https://www.alanvardy.com/posts/10
Additional reading about theming Bootstrap: https://getbootstrap.com/docs/4.0/getting-started/theming/

### PR DESCRIPTION
**Pull request by alanvardy**
Lets talk colors!

Added logo again, made the primary color red. Added fonts. Thoughts?

Closes #19 
Closes #18

### CODE REVIEW

**Comment by JoshMacSween** [comment]
The fonts are PERFECT! Good pick. 
I think the footer should be a black rectangle with white text. I think that will really pop with the charcoal background.

**Comment by alanvardy** [comment]
Awesome, I totally agree on the footer. I will get that footer changed and ask you again!

**Comment by alanvardy** [comment]
Take another look!

**Comment by JoshMacSween** [comment]
New look is fantastic! Only thing is when you go on the opportunities page, the 'new opportunities' link doesn't look too good to me. Maybe different shade? Or it could be white and underlined? I don't know.

**Comment by alanvardy** [comment]
Button fixed!

**Pull request merged**
